import { useState } from 'react';

const SENTIMENT_COLORS = {
  positive: { bg: '#052e16', text: '#4ade80', dot: '#22c55e' },
  neutral: { bg: '#0c1a2e', text: '#60a5fa', dot: '#3b82f6' },
  mixed: { bg: '#2d1b00', text: '#fbbf24', dot: '#f59e0b' },
  tense: { bg: '#1c0505', text: '#f87171', dot: '#ef4444' },
};

function Section({ color, title, children }) {
  return (
    <div style={{ marginBottom: 24 }}>
      <p
        style={{
          fontSize: 12,
          fontWeight: 700,
          color,
          letterSpacing: 0.5,
          textTransform: 'uppercase',
          marginBottom: 10,
          display: 'flex',
          alignItems: 'center',
          gap: 8,
        }}
      >
        <span
          style={{ width: 6, height: 6, borderRadius: '50%', background: color, display: 'inline-block' }}
        />
        {title}
      </p>
      {children}
    </div>
  );
}

function ListItem({ children, prefix }) {
  return (
    <div
      style={{
        fontSize: 14,
        color: '#cbd5e1',
        lineHeight: 1.65,
        padding: '7px 0',
        borderBottom: '1px solid #1e2535',
        display: 'flex',
        alignItems: 'flex-start',
        gap: 10,
      }}
    >
      <span style={{ marginTop: 6, flexShrink: 0, color: '#475569', fontSize: 12 }}>
        {prefix || '·'}
      </span>
      <span style={{ flex: 1 }}>{children}</span>
    </div>
  );
}

export default function Summary({ summary, savedPath, onReset, onRevealFile }) {
  const [copied, setCopied] = useState(false);
  const [transcriptCopied, setTranscriptCopied] = useState(false);

  const sentimentStyle = SENTIMENT_COLORS[summary.sentiment] || SENTIMENT_COLORS.neutral;

  const copyMarkdown = () => {
    const noRecorded = ['- None recorded'];
    const lines = [
      `# ${summary.title}`,
      '',
      `**TL;DR:** ${summary.tldr}`,
      '',
      '## Key Points',
      ...(summary.keyPoints?.length ? summary.keyPoints.map((p) => `- ${p}`) : noRecorded),
      '',
      '## Decisions',
      ...(summary.decisions?.length ? summary.decisions.map((d) => `- ${d}`) : noRecorded),
      '',
      '## Action Items',
      ...(summary.actionItems?.length
        ? summary.actionItems.map(
            (a) =>
              `- [ ] ${a.task}${a.owner ? ` *(${a.owner})` : ''}${a.deadline ? ` – ${a.deadline}` : ''}*`
          )
        : noRecorded),
      '',
      '## Next Steps',
      summary.nextSteps || '',
      '',
      `---`,
      `*Generated by Audist · ${new Date().toLocaleDateString()}*`,
    ].join('\n');

    navigator.clipboard.writeText(lines);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const S = {
    card: {
      background: '#111827',
      border: '1px solid #1e293b',
      borderRadius: 20,
      padding: 32,
      marginBottom: 16,
    },
    title: {
      fontSize: 24,
      fontWeight: 700,
      letterSpacing: '-0.5px',
      color: '#f1f5f9',
      marginBottom: 8,
      lineHeight: 1.3,
    },
    tldr: {
      fontSize: 15,
      color: '#94a3b8',
      lineHeight: 1.7,
      marginBottom: 24,
      paddingBottom: 24,
      borderBottom: '1px solid #1e293b',
    },
    metaRow: {
      display: 'flex',
      gap: 10,
      marginBottom: 24,
      flexWrap: 'wrap',
    },
    chip: {
      fontSize: 12,
      padding: '4px 10px',
      borderRadius: 20,
      fontWeight: 600,
    },
    actionChip: {
      fontSize: 11,
      padding: '2px 8px',
      borderRadius: 20,
      background: '#1e293b',
      color: '#64748b',
      marginLeft: 'auto',
      whiteSpace: 'nowrap',
      flexShrink: 0,
    },
    btnRow: {
      display: 'flex',
      gap: 10,
      justifyContent: 'flex-end',
      flexWrap: 'wrap',
    },
    resetBtn: {
      padding: '10px 20px',
      borderRadius: 10,
      border: 'none',
      background: 'transparent',
      color: '#475569',
      fontSize: 14,
      cursor: 'pointer',
    },
    outlineBtn: {
      padding: '10px 18px',
      borderRadius: 10,
      border: '1px solid #1e293b',
      background: '#1e293b',
      color: '#94a3b8',
      fontSize: 14,
      fontWeight: 600,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: 6,
    },
    copyBtn: {
      padding: '10px 20px',
      borderRadius: 10,
      border: '1px solid #1e293b',
      background: copied ? '#064e3b' : '#1e293b',
      color: copied ? '#6ee7b7' : '#94a3b8',
      fontSize: 14,
      fontWeight: 600,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: 6,
      transition: 'all 0.2s',
    },
  };

  return (
    <div style={{ animation: 'fadeIn 0.5s ease' }}>
      <div style={S.card}>
        <p
          style={{
            fontSize: 11,
            fontWeight: 700,
            letterSpacing: 1.5,
            textTransform: 'uppercase',
            color: '#475569',
            marginBottom: 14,
          }}
        >
          Meeting Summary
        </p>

        <h1 style={S.title}>{summary.title}</h1>
        <p style={S.tldr}>{summary.tldr}</p>

        {/* Meta chips */}
        <div style={S.metaRow}>
          {summary.sentiment && (
            <span
              style={{
                ...S.chip,
                background: sentimentStyle.bg,
                color: sentimentStyle.text,
              }}
            >
              <span
                style={{
                  width: 6,
                  height: 6,
                  borderRadius: '50%',
                  background: sentimentStyle.dot,
                  display: 'inline-block',
                  marginRight: 6,
                }}
              />
              {summary.sentiment.charAt(0).toUpperCase() + summary.sentiment.slice(1)} tone
            </span>
          )}
          {summary.speakers?.length > 0 && (
            <span style={{ ...S.chip, background: '#1e1b4b', color: '#818cf8' }}>
              {summary.speakers.length} participant{summary.speakers.length !== 1 ? 's' : ''}
            </span>
          )}
          {summary.actionItems?.length > 0 && (
            <span style={{ ...S.chip, background: '#1c1917', color: '#a78bfa' }}>
              {summary.actionItems.length} action item{summary.actionItems.length !== 1 ? 's' : ''}
            </span>
          )}
        </div>

        {/* Key Points */}
        {summary.keyPoints?.length > 0 && (
          <Section color="#6ee7b7" title="Key Points">
            {summary.keyPoints.map((p, i) => (
              <ListItem key={i}>{p}</ListItem>
            ))}
          </Section>
        )}

        {/* Decisions */}
        {summary.decisions?.length > 0 && (
          <Section color="#f59e0b" title="Decisions Made">
            {summary.decisions.map((d, i) => (
              <ListItem key={i} prefix="✓">
                {d}
              </ListItem>
            ))}
          </Section>
        )}

        {/* Action Items */}
        {summary.actionItems?.length > 0 && (
          <Section color="#818cf8" title="Action Items">
            {summary.actionItems.map((a, i) => (
              <div
                key={i}
                style={{
                  fontSize: 14,
                  color: '#cbd5e1',
                  lineHeight: 1.65,
                  padding: '7px 0',
                  borderBottom: '1px solid #1e2535',
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: 10,
                }}
              >
                <span style={{ marginTop: 3, flexShrink: 0, color: '#475569' }}>☐</span>
                <span style={{ flex: 1 }}>
                  {a.task}
                  {a.deadline && (
                    <span style={{ color: '#475569', fontSize: 12, marginLeft: 8 }}>
                      · {a.deadline}
                    </span>
                  )}
                </span>
                {a.owner && a.owner !== 'Team' && a.owner !== 'Unassigned' && (
                  <span style={S.actionChip}>{a.owner}</span>
                )}
              </div>
            ))}
          </Section>
        )}

        {/* Next Steps */}
        {summary.nextSteps && (
          <Section color="#38bdf8" title="Next Steps">
            <p style={{ fontSize: 14, color: '#94a3b8', lineHeight: 1.7 }}>{summary.nextSteps}</p>
          </Section>
        )}

        {/* Speakers */}
        {summary.speakers?.length > 0 && (
          <Section color="#a78bfa" title="Participants">
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {summary.speakers.map((s, i) => (
                <span
                  key={i}
                  style={{
                    fontSize: 13,
                    padding: '4px 12px',
                    borderRadius: 20,
                    background: '#1e1b4b',
                    color: '#c4b5fd',
                  }}
                >
                  {s}
                </span>
              ))}
            </div>
          </Section>
        )}
      </div>

      {/* Action row */}
      <div style={S.btnRow}>
        <button style={S.resetBtn} onClick={onReset}>
          ← New Meeting
        </button>
        {savedPath && (
          <button style={S.outlineBtn} onClick={onRevealFile}>
            🎵 Show Recording
          </button>
        )}
        <button style={S.copyBtn} onClick={copyMarkdown}>
          {copied ? '✓ Copied!' : '⎘ Copy as Markdown'}
        </button>
      </div>
    </div>
  );
}
